apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
  namespace: default
type: Opaque
stringData:
  superUserPassword: {{ secrets.SUPERUSER_PASSWORD }}
  replicationUserPassword: {{ secrets.REPLICATION_USER_PASSWORD }}
